### ISSUE TITLE
Something about this API key

### ISSUE THREAD

**Issue by kpatenio** [adas-team/ElectionsApp#18]
Idk anything about Firebase aside from the fact that it's similar to nosql. But I see [here](https://github.com/adas-team/ElectionsApp/blob/65e34f4af8543b9e7a91a34bd7fb2784c54bc1be/src/firebase/firebase.js#L5) that the API key is exposed. Is this a security concern?

If so (and if time permits), if you can find a way to hide this piece of information (probably once deployment is figured out), that would be awesome :)

**Comment by xiangxinyue** [comment]
Yes, we will try to work at it. Either using or Library BFG.

Ref:
https://rtyley.github.io/bfg-repo-cleaner/
git-filter-branch https://git-scm.com/docs/git-filter-branch
https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
