### ISSUE TITLE
Security: Hide API keys and mailing list members

### ISSUE THREAD

**Issue by HelenGezahegn** [adas-team/ElectionsApp#21]
We need to make `securityAccountKey.json` and `mailingList.json` private in our repo.

**Comment by xiangxinyue** [comment]
Yes, we will try to work at it. Either using or Library BFG.

Ref:
https://rtyley.github.io/bfg-repo-cleaner/
git-filter-branch https://git-scm.com/docs/git-filter-branch
https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
